apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: kube-system

spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: '' #TODO: YOUR EMAIL ADDRESS
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
    dns01:
      providers:
      - name: gcp-dns
        clouddns:
          serviceAccountSecretRef:
            name: clouddns-service-account
            key: cert-manager-key.json
          project: '' #TODO: YOUR GCP PROJECT
